version: '3.8'

services:
  # VICTOR-TTS UNIFIED API Server
  victor-tts-api:
    build: .
    container_name: victor-tts-api
    ports:
      - "6969:6969"  # Main API for N8N
      - "7000:7000"  # Web Interface
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Bangkok
      - VICTOR_TTS_MODE=docker
      - VICTOR_TTS_N8N_INTEGRATION=true
    volumes:
      - ./storage:/app/storage
      - ./models:/app/models
      - ./logs:/app/logs
      - ./config:/app/config
      - ./voice_models:/app/voice_models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - victor-network

  # N8N Workflow Automation (Simple)
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_BASIC_AUTH_ACTIVE=false
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Bangkok
      - N8N_VICTOR_TTS_URL=http://victor-tts-api:6969
      - N8N_VICTOR_TTS_WEB_URL=http://victor-tts-api:7000
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_workflows:/home/node/.n8n/workflows
    restart: unless-stopped
    depends_on:
      victor-tts-api:
        condition: service_healthy
    networks:
      - victor-network

volumes:
  n8n_data:

networks:
  victor-network:
    driver: bridge 