services:
  # VICTOR-TTS API Server (Test Mode)
  victor-tts-test:
    build: .
    container_name: victor-tts-test
    ports:
      - "6969:6969"  # API
      - "7000:7000"  # Web Interface
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Bangkok
      - VICTOR_TTS_MODE=test
      - VICTOR_TTS_N8N_INTEGRATION=true
      - VICTOR_TTS_LOG_LEVEL=DEBUG
    volumes:
      - ./storage:/app/storage
      - ./models:/app/models
      - ./logs:/app/logs
      - ./config:/app/config
      - ./voice_models:/app/voice_models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - test-network

  # N8N Test Instance
  n8n-test:
    image: n8nio/n8n:latest
    container_name: n8n-test
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_BASIC_AUTH_ACTIVE=false
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Bangkok
      - N8N_VICTOR_TTS_URL=http://victor-tts-test:6969
      - N8N_VICTOR_TTS_WEB_URL=http://victor-tts-test:7000
    volumes:
      - n8n_test_data:/home/node/.n8n
      - ./n8n_workflows:/home/node/.n8n/workflows
    restart: unless-stopped
    depends_on:
      victor-tts-test:
        condition: service_healthy
    networks:
      - test-network

volumes:
  n8n_test_data:

networks:
  test-network:
    driver: bridge 