# 🔧 VICTOR-TTS UNIFIED Configuration
# ไฟล์ config หลักสำหรับระบบที่จัดระเบียบใหม่

# ========================================
# ระบบหลัก (Main System)
# ========================================

[system]
name = "VICTOR-TTS UNIFIED"
version = "3.0.0-UNIFIED"
description = "Complete TTS + Voice Conversion Platform"

# ========================================
# ไดเรกทอรี (Directories)
# ========================================

[directories]
# โฟลเดอร์สำหรับเก็บโมเดล RVC
models_dir = "models"
# สำรองข้อมูล: ใช้ logs ถ้าไม่มี models
models_dir_fallback = "logs"

# โฟลเดอร์สำหรับไฟล์ชั่วคราว
temp_dir = "storage/temp"

# โฟลเดอร์สำหรับไฟล์ผลลัพธ์
output_dir = "storage/output"

# โฟลเดอร์สำหรับ config files
config_dir = "config"

# โฟลเดอร์สำหรับไฟล์เก่า
legacy_dir = "legacy"

# ========================================
# การตั้งค่า GPU (GPU Settings)
# ========================================

[gpu]
# เปิดใช้งาน GPU
enabled = true

# GPU ID ที่ต้องการใช้ (0, 1, 2, ...)
# -1 หมายถึงใช้ CPU
device_id = 0

# จำกัดหน่วยความจำ GPU (MB) - 0 หมายถึงไม่จำกัด
memory_limit = 0

# ใช้ mixed precision (FP16) เพื่อความเร็วและประหยัดหน่วยความจำ
use_fp16 = true

# ========================================
# การตั้งค่า TTS (Text-to-Speech)
# ========================================

[tts]
# ขนาดสูงสุดของข้อความ (ตัวอักษร)
max_text_length = 10000000

# ขนาดสูงสุดของแต่ละ chunk (ตัวอักษร)
max_chunk_size = 8000

# ความเร็วเริ่มต้น
default_speed = 1.0

# เสียงเริ่มต้น
default_voice = "th-TH-PremwadeeNeural"

# ========================================
# การตั้งค่า RVC (Voice Conversion)
# ========================================

[rvc]
# เปิดใช้งาน RVC
enabled = true

# การตั้งค่าเริ่มต้น
default_transpose = 0
default_index_ratio = 0.75
default_f0_method = "rmvpe"

# ========================================
# การตั้งค่า API Server
# ========================================

[api_server]
# Host และ Port
host = "0.0.0.0"
port = 6969

# ขนาดไฟล์สูงสุดที่อัปโหลดได้ (bytes)
max_file_size = 52428800  # 50MB

# เวลาในการ cleanup ไฟล์ชั่วคราว (วินาที)
cleanup_interval = 3600  # 1 ชั่วโมง

# ========================================
# การตั้งค่า Web Interface
# ========================================

[web_interface]
# Port สำหรับ Web Interface
port = 7000

# เปิดเบราว์เซอร์อัตโนมัติ
auto_open_browser = true

# ========================================
# เสียงที่รองรับ (Supported Voices)
# ========================================

[voices.th-TH-PremwadeeNeural]
name = "Premwadee (Thai Female)"
gender = "Female"
language = "Thai"

[voices.th-TH-NiranNeural]
name = "Niran (Thai Male)"
gender = "Male"
language = "Thai"

[voices.en-US-AriaNeural]
name = "Aria (US Female)"
gender = "Female"
language = "English"

[voices.en-US-GuyNeural]
name = "Guy (US Male)"
gender = "Male"
language = "English"

[voices.en-US-JennyNeural]
name = "Jenny (US Female)"
gender = "Female"
language = "English"

[voices.ja-JP-NanamiNeural]
name = "Nanami (Japanese Female)"
gender = "Female"
language = "Japanese"

[voices.zh-CN-XiaoxiaoNeural]
name = "Xiaoxiao (Chinese Female)"
gender = "Female"
language = "Chinese"

# ========================================
# การ Log (Logging)
# ========================================

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file = "storage/output/victor-tts.log"

# ========================================
# การตั้งค่าขั้นสูง (Advanced Settings)
# ========================================

[advanced]
# จำนวน worker processes
workers = 1

# เปิดใช้งาน debug mode
debug = false

# Retry ครั้งสูงสุดสำหรับ TTS
max_retries = 3

# หน่วงเวลาระหว่าง chunk (วินาที)
chunk_delay = 0.1
